version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./master_Dockerfile
    working_dir: /root/playbooks
    volumes:
      - /home/bakary/devops/docker/docker_ansible/playbooks:/root/playbooks
      - /home/bakary/devops/docker/docker_ansible/config:/etc/ansible
    command: tail -f /dev/null
    
  serveurs_web:
    build:
      context: .
      dockerfile: ./server_Dockerfile

  database:
    build:
      context: .
      dockerfile: ./server_Dockerfile

  loadbalancer:
    build:
      context: .
      dockerfile: ./server_Dockerfile
    ports: 
    - 8080:80